### ISSUE TITLE
running LASHiS

### ISSUE THREAD

**Issue by caitaylo** [thomshaw92/LASHiS#1]
Originally I tired to run the following:
/crash-work/caitlin/28andme/mri_LASHiS/LASHiS-master/LASHiS.sh -a ./crash-work/caitlin/ashs/atlases/ashs_atlas_princeton/ \
-g 1 -n 1 \
-o 28andLASHiS \
 /crash-work/caitlin/28andme/mri_LASHiS/D01/anat/t1_mprage_0_8mm.nii /crash-work/caitlin/28andme/mri_LASHiS/D01/anat/t2_tse_tra_hi_res_hippocampus.nii \\\\
 /crash-work/caitlin/28andme/mri_LASHiS/D02/anat/t1_mprage_0_8mm.nii /crash-work/caitlin/28andme/mri_LASHiS/D02/anat/t2_tse_tra_hi_res_hippocampus.nii \\\

Per the instructions below I misunderstood the use of \\\ which was giving me errors. 

"anatomical images                          Set of multimodal (T1w or gradient echo, followed by T2w FSE/TSE input) data. Data must be in the format specified by ASHS & ordered as follows:
                                                  \${time1_T1w} \${time1_T2w} \\\\
                                                  \${time2_T1w} \${time2_T2w} ...
                                                  .
                                                  .
                                                  .
                                                   \${timeN_T1w} \${timeN_T2w} ..."

Per your recommendations I removed the \\\ as well as the -g and -n commands and added -c 2

Thanks for your help

**Comment by thomshaw92** [comment]
Hi Caitlin,
Sorry for that, there was an extra \ in the readme. I've fixed it up now. 
(p.s., denoising and N4 have been incorporated now)
Cheers,
Tom
