### ISSUE TITLE
Qeustions about the subfield label stats

### ISSUE THREAD

**Issue by ash077** [thomshaw92/LASHiS#7]
Hi, I'm confused with the output of subfield label stats. Why do different subfields contain similar/same numbers of voxels but their volumes are largerly different?
Here is one subject's output:

> sub-004 left CA1 22 1604.080
> sub-004 left CA2 10 13.046
> sub-004 left DG 18 989.380
> sub-004 left CA3 9 57.983
> sub-004 left misc 17 263.138
> sub-004 left SUB 21 556.259
> sub-004 left ERC 13 611.343
> sub-004 left BA35 14 655.289
> sub-004 left BA36 15 2907.791
> sub-004 left PHC 12 1468.201
> sub-004 left sulcus 23 758.514

And the readme file says:
Columns: {side} {subfield name} {number of voxels containing the label} **{volume in mm^2}**
I think here should be volume in mm^3?

Thanks!

**Comment by thomshaw92** [comment]
Thanks for the feedback @ash077 
I'll have a look through and get back to you soon. 

Would you mind please sending me the output from your run?

I've updated the README - thanks for spotting the error!

**Comment by thomshaw92** [comment]
Hi @ash077 I've dug into the original code for stats export:
https://github.com/pyushkevich/ashs/blob/4595fdaefcbe49ed6d3c8e788f22dbb429c26d40/bin/ashs_extractstats_qsub.sh 

Seems like we are actually exporting the 'extent along the Z-axis.'

I've updated the README to reflect this and apologise for the confusion!
You can use ANTs or similar to get the voxel count of each label.
